export const CURRICULO_3: Record<string, string[]> = {
  "1º Período": [
    "Algoritmos e Estruturas de Dados I",
    "Cálculo I",
    "Desenvolvimento de Interfaces Web",
    "Fundamentos de Engenharia de Software",
    "Introdução à Computação",
    "Trabalho Interdisciplinar: Aplicações Web",
  ],
  "2º Período": [
    "Arquitetura de Computadores",
    "Bancos de Dados",
    "Cálculo II",
    "Laboratório de Programação Modular",
    "Modelagem de Processos de Negócios",
    "Programação Modular",
    "Trabalho Interdisciplinar: Aplicações para Processos de Negócios",
  ],
  "3º Período": [
    "Algoritmos e Estruturas de Dados II",
    "Engenharia de Requisitos de Software",
    "Introdução à Pesquisa em Informática",
    "Sistemas Operacionais",
    "Trabalho Interdisciplinar: Aplicações para Cenários Reais",
  ],
  "4º Período": [
    "Interação Humano-Computador",
    "Laboratório de Desenvolvimento de Software",
    "Optativa I",
    "Projeto de Software",
    "Redes de Computadores",
    "Teoria dos Grafos e Computabilidade",
    "Trabalho Interdisciplinar: Aplicações para Sustentabilidade",
  ],
  "5º Período": [
    "Arquitetura de Software",
    "Desenvolvimento de Aplicações Móveis e Distribuídas",
    "Estatística e Probabilidade",
    "Fundamentos de Projeto e Análise de Algoritmos",
    "Gerência de Projetos de Software",
    "Laboratório de Desenvolvimento de Aplicações Móveis e Distribuídas",
    "Optativa II",
    "Trabalho Interdisciplinar: Aplicações Distribuídas",
  ],
  "6º Período": [
    "Engenharia Econômica para Software",
    "Gerência de Configuração e Evolução de Software",
    "Laboratório de Experimentação de Software",
    "Medição e Experimentação em Engenharia de Software",
    "Optativa III",
    "Teste de Software",
    "Trabalho Interdisciplinar: Pesquisa em Engenharia de Software",
  ],
  "7º Período": [
    "Computadores e Sociedade",
    "Engenharia de Processos e Qualidade de Software",
    "Gestão da Produção de Software",
    "Tecnologias da Informação e do Conhecimento",
    "Tópicos em Computação I",
    "Tópicos em Computação II",
    "Trabalho de Conclusão de Curso I",
  ],
  "8º Período": [
    "Modelagem e Avaliação de Desempenho",
    "Optativa IV",
    "Segurança e Auditoria de Sistemas",
    "Tópicos em Engenharia de Software",
    "Tópicos em Sistemas de Software",
    "Trabalho de Conclusão de Curso II",
  ],
};

export const CURRICULO_4: Record<string, string[]> = {
  "1º Período": [
    "Computabilidade",
    "Desenvolvimento de Interfaces Web",
    "Fundamentos de Engenharia de Software",
    "Introdução à Algoritmos",
    "Introdução à Computação",
    "Trabalho Interdisciplinar: Desenvolvimento de Aplicações Web",
  ],
  "2º Período": [
    "Arquitetura de Computadores",
    "Cálculo I",
    "Desenvolvimento e Integração de Aplicações Web",
    "Interação Humano-Computador",
    "Introdução à Pesquisa em Informática",
    "Metodologias de Extensão Universitária",
    "Programação Modular",
    "Trabalho Interdisciplinar: Desenvolvimento Centrado no Usuário",
  ],
  "3º Período": [
    "Bancos de Dados",
    "Cálculo II",
    "Engenharia de Requisitos de Software",
    "Estruturas de Dados",
    "Fundamentos de Sistemas Operacionais",
    "Trabalho Interdisciplinar: Desenvolvimento de Aplicações para Sustentabilidade",
  ],
  "4º Período": [
    "Algoritmos em Grafos",
    "Cultura e Práticas DevOps",
    "Desenvolvimento de Carreira Internacional",
    "Gerência de Projetos de Software",
    "Gerência de Requisitos de Software",
    "Optativa I",
    "Projeto de Software",
    "Redes de Computadores",
    "Trabalho Interdisciplinar: Desenvolvimento de Sistemas em Ambientes de Produção",
  ],
  "5º Período": [
    "Análise e Projeto de Algoritmos",
    "Desenvolvimento de Aplicações Móveis",
    "Engenharia Econômica para Software",
    "Estatística e Probabilidade",
    "Fundamentos de Inteligência Artificial",
    "Gestão da Produção de Software",
    "Sistemas Distribuídos e Computação em Nuvem",
    "Trabalho Interdisciplinar: Desenvolvimento de Aplicações Inovadoras",
  ],
  "6º Período": [
    "Arquitetura de Software",
    "Ciência de Dados e Inteligência Artificial",
    "Modelagem e Avaliação de Desempenho",
    "Optativa II",
    "Segurança em Desenvolvimento de Software",
    "Teste de Software",
    "Tópicos Especiais em Sistemas Computacionais",
    "Trabalho Interdisciplinar: Engenharia de Arquiteturas Avançadas",
  ],
  "7º Período": [
    "Design de Interação e Experiência de Usuário",
    "Medição e Experimentação em Engenharia de Software",
    "Métodos Formais em Engenharia de Software",
    "Seminários Avançados em Engenharia de Software",
    "Site Reliability Engineering (SRE)",
    "Tópicos Especiais em Engenharia de Software",
    "Trabalho Interdisciplinar: Pesquisa e Avaliação Empírica",
  ],
  "8º Período": [
    "Cidadania e Responsabilidade Social",
    "Engenharia de Processos de Software",
    "Manutenção e Evolução de Software",
    "Modelagem de Processos de Negócios",
    "Qualidade de Software",
    "Trabalho de Conclusão de Curso",
  ],
};
